package com.timesheet.domain;

// default package
// Generated Feb 18, 2018 3:41:47 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "timesheet")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8265127921786950582L;
	private Integer empId;
	private Organisation organisation;
	private String designation;
	private String email;
	private String empName;
	private String gender;
	private LocalDate joinDate;
	private Set<Timelog> timelogs = new HashSet<Timelog>(0);

	public Employee() {
	}

	public Employee(Organisation organisation) {
		this.organisation = organisation;
	}

	public Employee(Organisation organisation, String designation, String email, String empName, String gender,
			LocalDate joinDate, Set<Timelog> timelogs) {
		this.organisation = organisation;
		this.designation = designation;
		this.email = email;
		this.empName = empName;
		this.gender = gender;
		this.joinDate = joinDate;
		this.timelogs = timelogs;
	}

	public Employee(String empName, LocalDate joinDate, String gender, String designation, String email) {
		// TODO Auto-generated constructor stub
		this.empName = empName;
		this.joinDate = joinDate;
		this.gender = gender;
		this.designation = designation;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "emp_id", unique = true, nullable = false)
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "designation", length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "emp_name", length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "join_date", length = 10)
	public LocalDate getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(LocalDate joinDate) {
		this.joinDate = joinDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Timelog> getTimelogs() {
		return this.timelogs;
	}

	public void setTimelogs(Set<Timelog> timelogs) {
		this.timelogs = timelogs;
	}

	public void addLog(Timelog log) {
		Set<Timelog> set = this.getTimelogs();
		set.add(log);
		this.setTimelogs(set);
	}

}
